language: r

cache: packages

r:
- oldrel
- release
- devel

notifications:
  email: false
  hipchat:
    rooms:
      secure: vUjocl7degf8x97m8AtQuW3HAjxxPSd3gBVCBhRKYWaCWu2LDEJVV2RMYFxDAEFkbzcO3jJdJmIEqWblkTBnTZMWWK4wBjur9Pi0+GaFNDtduKYYWiAabS+BLoPmmT1k4dOMzUQkckKPnDmgV1wQLFQaaeSg0obMeZvfuRpggQPRsNjgyICCDGs8MJngC7UkcIDaJTixZAoqyZVulctgIxHSD/zAClEhC1JnLddRpoLswv9wS+XZ3UlCMHyPIRklfXmnhs0R9Akjl7brZD2kq1OgF3NxHlVTpJqwhGy4Vf7G0LbNDLtC2lOq4pqYrpn/SPGYvedMT5PvZz6IKFf4mm2Lfm5wzflnTvjYVaYLJ5s2ZvB8J65caPc5qEVUk9U77XWma2BALiNdHNeH0EofbNgS2Db0ACepAAygDwNSgRNucOoDxw7PAwLNKE9Umn4zK8a5veTXYLXIFVagBAGr0aFBIWhlJylY+nFMmSf6jyl2itp5mjYm81KlVY+U2XaDR+o1lxXxNnMfynGbzrofEweDwMFFy+NjhPJiUMTdB/bXOAl18vdKxY5t70gmCiY6ZFkiYjmGZc45Ac0tahoCibQRRP1oABOXNPuIw0y83Pdok1GrC+0HXPGYnbLXaeH0CpbEXc2QngW6Cp4qLfZWVzTMwPMqzwVWDV4faTn3hKo=
